In [3]:
import numpy  as np

In [4]:
a  = [i for i in range(10)]

In [5]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
b =  np.array(a)

In [7]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b = np.array(a)

In [68]:
b

array([1, 2, 3], dtype=int64)

In [10]:
b = np.array([i for i in range(10)])

In [11]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
type(b)

numpy.ndarray

In [13]:
b = np.array(a, dtype = float)

In [14]:
a = [0,1,2,3,4,5,6,7,8,9.9]


In [15]:
b = np.array(a, dtype = float)

In [16]:
b

array([0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9.9])

In [17]:
b = np.array(a, dtype = str)

In [18]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

In [19]:
a = ['abc', 1, 2, 3]

In [20]:
b = np.array(a)

In [21]:
b

array(['abc', '1', '2', '3'], dtype='<U11')

In [22]:
a = [0,1,2,3.125]

In [23]:
b = np.array(a)

In [24]:
b

array([0.   , 1.   , 2.   , 3.125])

In [25]:
b.dtype

dtype('float64')

In [26]:
b[0]

0.0

In [27]:
b[1]

1.0

In [28]:
b[2]

2.0

In [29]:
b[3]

3.125

In [30]:
b.ndim

1

In [31]:
b.shape

(4,)

In [32]:
b = np.array([[0,1,2,3,4,5,6,7,8,9],
            [10,11,12,13,14,15,16,17,18,19],
            [20,21,22,23,24,25,26,27,28,29]])

In [33]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
b.shape

(3, 10)

In [35]:
b.size

30

In [36]:
b[0][0]

0

In [37]:
b[2,5]

25

In [38]:
b[0:2, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [39]:
b[:2, :3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [40]:
b[1:, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [41]:
c = b[1:, 5:]

In [42]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [43]:
c[1, 4] = 999

In [44]:
c

array([[ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [45]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [46]:
b[1,5] = 555

In [47]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 555,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [48]:
c

array([[555,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [49]:
c = b[1:, 5:].copy()

In [50]:
c

array([[555,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [51]:
c[0,0] = 777

In [52]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 555,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [53]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [54]:
b[1,5] = 888

In [55]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 888,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [56]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

## Data types

In [57]:
b = np.array([1., 2., 3.], dtype = np.float32)


In [58]:
b

array([1., 2., 3.], dtype=float32)

In [59]:
b = np.array([1., 2., 3.], dtype = np.float64)

In [60]:
b

array([1., 2., 3.])

In [61]:
b.dtype

dtype('float64')

In [62]:
b = np.array([1, 2, 3], dtype = np.int32)

In [63]:
b

array([1, 2, 3])

In [64]:
b.dtype

dtype('int32')

In [65]:
b = np.array([1,2,3], dtype = np.int64)

In [66]:
b


array([1, 2, 3], dtype=int64)

In [67]:
b.dtype

dtype('int64')