In [147]:
import numpy  as np

In [148]:
a  = [i for i in range(10)]

In [149]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [150]:
b =  np.array(a)

In [151]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
b = np.array(a)

In [153]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
b = np.array([i for i in range(10)])

In [155]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
type(b)

numpy.ndarray

In [157]:
b = np.array(a, dtype = float)

In [158]:
a = [0,1,2,3,4,5,6,7,8,9.9]


In [159]:
b = np.array(a, dtype = float)

In [160]:
b

array([0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9.9])

In [161]:
b = np.array(a, dtype = str)

In [162]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

In [163]:
a = ['abc', 1, 2, 3]

In [164]:
b = np.array(a)

In [165]:
b

array(['abc', '1', '2', '3'], dtype='<U11')

In [166]:
a = [0,1,2,3.125]

In [167]:
b = np.array(a)

In [168]:
b

array([0.   , 1.   , 2.   , 3.125])

In [169]:
b.dtype

dtype('float64')

In [170]:
b[0]

0.0

In [171]:
b[1]

1.0

In [172]:
b[2]

2.0

In [173]:
b[3]

3.125

In [174]:
b.ndim

1

In [175]:
b.shape

(4,)

In [176]:
b = np.array([[0,1,2,3,4,5,6,7,8,9],
            [10,11,12,13,14,15,16,17,18,19],
            [20,21,22,23,24,25,26,27,28,29]])

In [177]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [178]:
b.shape

(3, 10)

In [179]:
b.size

30

In [180]:
b[0][0]

0

In [181]:
b[2,5]

25

In [182]:
b[0:2, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [183]:
b[:2, :3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [184]:
b[1:, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [185]:
c = b[1:, 5:]

In [186]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [187]:
c[1, 4] = 999

In [188]:
c

array([[ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [189]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [190]:
b[1,5] = 555

In [191]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 555,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [192]:
c

array([[555,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [193]:
c = b[1:, 5:].copy()

In [194]:
c

array([[555,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [195]:
c[0,0] = 777

In [196]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 555,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [197]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [198]:
b[1,5] = 888

In [199]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 888,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [200]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

## Data types

In [201]:
b = np.array([1., 2., 3.], dtype = np.float32)


In [202]:
b

array([1., 2., 3.], dtype=float32)

In [203]:
b = np.array([1., 2., 3.], dtype = np.float64)

In [204]:
b

array([1., 2., 3.])

In [205]:
b.dtype

dtype('float64')

In [206]:
b = np.array([1, 2, 3], dtype = np.int32)

In [207]:
b

array([1, 2, 3])

In [208]:
b.dtype

dtype('int32')

In [209]:
b = np.array([1,2,3], dtype = np.int64)

In [210]:
b


array([1, 2, 3], dtype=int64)

In [211]:
b.dtype

dtype('int64')