In [82]:
import numpy as np

### Автоматическое создание массивов

In [83]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [85]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

По умолчанию ряд чисел начинается с 0, но можно явно задачть начало последовательности

In [86]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Последовательность с шагом 2:

In [87]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

В обратном порядке

In [88]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

В обратном порядке с шагом 2:


In [89]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

Дробный шаг


In [90]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

<b> numpy.linspace </b> - то же самое, но нужно учитывать, что правая граница (9.9) будет включена.

Вместо шага указывем нужное число элементов (100):

In [91]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

<b> numpy.logspace </b> - обе границы также включены, но это не сами числа, а степени числа 10:

In [92]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

### Генерация случайных чисел

<b> numpy.random.sample </b>  - случайные числас равномерным распределением в промежутке [0.0, 1.0).

Случайное число

In [93]:
np.random.sample()

0.5986584841970366

Одномерный массив из 3 чисел

In [94]:
np.random.sample(3)

array([0.15601864, 0.15599452, 0.05808361])

Двумерный массив 2x3:

In [95]:
np.random.sample((2,3))

array([[0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264]])

Массив 48x64x3

(Например, это может быть случайное изображение с высотой 48, шириной 64 и значениями яркости трех цветов для каждого пикселя):

In [96]:
np.random.sample((64, 48, 3))

array([[[0.21233911, 0.18182497, 0.18340451],
        [0.30424224, 0.52475643, 0.43194502],
        [0.29122914, 0.61185289, 0.13949386],
        ...,
        [0.05147875, 0.27864646, 0.90826589],
        [0.23956189, 0.14489487, 0.48945276],
        [0.98565045, 0.24205527, 0.67213555]],

       [[0.76161962, 0.23763754, 0.72821635],
        [0.36778313, 0.63230583, 0.63352971],
        [0.53577468, 0.09028977, 0.8353025 ],
        ...,
        [0.82260056, 0.36019064, 0.12706051],
        [0.52224326, 0.76999355, 0.21582103],
        [0.62289048, 0.08534746, 0.05168172]],

       [[0.53135463, 0.54063512, 0.6374299 ],
        [0.72609133, 0.97585208, 0.51630035],
        [0.32295647, 0.79518619, 0.27083225],
        ...,
        [0.07276301, 0.82186006, 0.70624223],
        [0.08134878, 0.08483771, 0.98663958],
        [0.3742708 , 0.37064215, 0.81279957]],

       ...,

       [[0.50677004, 0.12654531, 0.47662046],
        [0.7636153 , 0.25826436, 0.48078617],
        [0.99201597, 0

<b> numpy.random.randn </b> - случайные числа с нормальным распределением

(среднее значение = 0, среднеквадратичное отклонение = 1)


In [97]:
np.random.randn(10)

array([-0.17414072,  1.71418347,  1.68659614, -0.33016967, -0.08102384,
       -0.02236886, -0.00896633, -0.94742905, -1.08726068,  1.24975757])

In [98]:
np.random.randn(3, 4)

array([[ 1.08978701,  1.07252071, -0.06937837,  1.89201177],
       [-0.02246898,  0.86287617, -1.38862201, -0.22973533],
       [-0.15582106, -0.06548754, -1.32549897,  0.70388093]])

<b> numpy.random.randint </b> - массив из целых чисел

Например, одномерный массив из 10 случайных чисел в промежутке [0, 100);

In [99]:
np.random.randint(0, 100, 10)

array([28, 46, 29, 89, 83, 37, 82, 26, 88, 86])

Двумерный массив 3х4 из случайных целых чисел в промежутке [0, 10):

In [100]:
np.random.randint(0, 10, (3, 4))

array([[2, 9, 7, 0],
       [2, 4, 4, 9],
       [1, 9, 7, 4]])

<b>numpy.random.choice</b> - случайный выбор элементов из массива

In [101]:
b = np.array([1, 5, 2, 7, 3, 8, 6, 4])

In [102]:
np.random.choice(b)

6

In [103]:
np.random.choice(b, 3)

array([6, 4, 6])

In [104]:
np.random.seed(42)

In [105]:
np.random.randint(0, 10, 3)

array([6, 3, 7])

### Изменение формы массива

In [106]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
a.reshape (3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [109]:
# Можно указать требуемое число строк, а вместо числа столбцов поставить -1
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
# Указано только число столбцов
np.reshape(a, (- 1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [112]:
# inplace
a.resize(3, 4)

In [113]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Соединение массивов

Для наглядности возьмем два массива - с нулями и единицами:

In [115]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [116]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [117]:
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [118]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

In [119]:
np.concatenate((a, b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

Создание столбцов (в горизонтальном измерении)

In [120]:
h = np.hstack((a, b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [122]:
a.shape, b.shape, h.shape

((2, 3), (2, 3), (2, 6))

In [123]:
np.concatenate((a,  b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

Соудинение в глубину (в третьем измерении)

In [124]:
d = np.dstack([a, b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])