### Операции с векторами

Загрузим библиотеку NumPy

In [1]:
import numpy as np

In [3]:
a = np.array([0, 1, 2, 3, 4])

In [4]:
b = np.array([5, 6, 7, 8, 9])

In [5]:
a.size

5

In [6]:
b.size

5

In [7]:
a.shape

(5,)

In [8]:
b.shape

(5,)

### Сложение векторов

In [9]:
c = a + b

In [10]:
c

array([ 5,  7,  9, 11, 13])

Сравним, что делает оператор "+" со списками в Python:

In [11]:
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]

In [12]:
x1 + x2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Еще один способ:

In [13]:
c = np.add(a, b)
c

array([ 5,  7,  9, 11, 13])

### Вычитание векоров

In [14]:
a = np.array([5, 4, 8, 4, 3])
b = np.array([3, 5, 7, 1, 3])

In [15]:
d = a - b
d

array([ 2, -1,  1,  3,  0])

Альтернативный способ

In [18]:
d = np.subtract(a, b)
d

array([ 2, -1,  1,  3,  0])

In [19]:
a.shape == b.shape

True

### Умножение вектора на скаляр

In [20]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [21]:
c = a * 2
c

array([10,  8, 16,  8,  6])

In [22]:
c = -10 * a
c

array([-50, -40, -80, -40, -30])

In [23]:
c = 0.5 * a
c

array([2.5, 2. , 4. , 2. , 1.5])

Сравним с умножением натурального числа на список

(результат не тот - увеличение длины списка, а не умножение вектора на скаляр):

In [24]:
2 * [1, 2, 3]

[1, 2, 3, 1, 2, 3]

Альтернативные способы умножения массива на скаляр:

In [25]:
a = np.array([5, 4, 8, 4, 3])

In [26]:
a

array([5, 4, 8, 4, 3])

In [27]:
# Вариант 1
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [28]:
# Вариант 2
np.dot(-10, a)

array([-50, -40, -80, -40, -30])

In [29]:
# Вариант 3
np.multiply(-10, a)

array([-50, -40, -80, -40, -30])

### Скалярное произведение векторов

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [31]:
a.shape

(3,)

In [32]:
b.shape

(3,)

In [33]:
sp = a[0] *  b[0] + a[1] * b[1] + a[2] * b[2]
sp

32

In [34]:
a @ b

32

In [35]:
sp = np.dot(a, b)

In [36]:
sp

32

### Операции с матрицами

In [37]:
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

In [38]:
B = np.array([[6, 7],
              [8, 9],
              [10, 11]])

In [39]:
A.shape

(3, 2)

In [40]:
B.shape

(3, 2)

### Сложение матриц

In [42]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

Альтернативный способ:


In [43]:
C = np.add(A, B)

In [44]:
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

### Вычитание матриц

In [45]:
A = np.array([[11, 13],
              [2, 3],
              [4, 5]])

In [48]:
B = np.array([[6, 7],
             [8, 9],
             [10, 11]])

In [49]:
D = A - B
D

array([[ 5,  6],
       [-6, -6],
       [-6, -6]])

In [50]:
D = np.subtract(A, B)
D

array([[ 5,  6],
       [-6, -6],
       [-6, -6]])

### Умножение матрицы на скаляр

In [51]:
X = np.array([[1, 2], [3, 4]])

In [52]:
X

array([[1, 2],
       [3, 4]])

In [53]:
Y = X * 3
Y

array([[ 3,  6],
       [ 9, 12]])

In [56]:
Y = np.dot(X, 3)
Y

array([[ 3,  6],
       [ 9, 12]])