In [19]:
import numpy as np

### Выбор данных

In [20]:
a = np.random.randint(0, 20, 10)
a

array([ 1, 19,  7,  3, 12, 10, 18,  7,  4,  8])

In [21]:
a[a > 10]

array([19, 12, 18])

In [22]:
a[(a > 10) & (a % 2 == 0)]

array([12, 18])

In [23]:
a[(a > 10) | (a % 3 == 0)]

array([19,  3, 12, 18])

<b>numpy.where</b> - первый вариант применения

In [24]:
a

array([ 1, 19,  7,  3, 12, 10, 18,  7,  4,  8])

In [25]:
# Возвращает индексы чисел, удовлетворяющих условию 
np.where(a > 10)

(array([1, 4, 6], dtype=int64),)

In [26]:
a[np.where(a > 10)]

array([19, 12, 18])

<b>numpy.where</b> - второй вариант применения

In [27]:
a = [1, 4, 7]
b = [9, 2, 5]

In [28]:
# Если в условии True, то берем элемент из массива a,
# Если False - то из b
np.where([True, False, True], a, b)

array([1, 2, 7])

### Сортировка

In [29]:
a = np.array([[1, 3, 9, 9],
              [5, 0, 1, 5],
              [2, 7, 3, 5]])

In [30]:
a[[0,  2, 1],  :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [31]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]], dtype=int64)

In [32]:
a[:, 0].argsort()

array([0, 2, 1], dtype=int64)

In [34]:
a[a[:, 0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

### Случайное перемешивание массивов

Одномерные массивы

In [35]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# inplace - на месте
np.random.shuffle(a)

In [37]:
a

array([6, 5, 0, 9, 7, 4, 8, 2, 3, 1])

Двумерные массивы

In [40]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
# inplace
np.random.shuffle(a)

In [42]:
a

array([[ 6,  7,  8],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 3,  4,  5]])

### Математические действия с массивами

Применение математических функций ко всему массиву

In [43]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
# Логарифм по основанию е
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [45]:
# Экспонента
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [46]:
a.sum()

21

In [47]:
a.sum(axis = 0)

array([5, 7, 9])

In [48]:
a.sum(axis = 1)

array([ 6, 15])

In [49]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

Поэлементное (не матричное) умножение

In [52]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
b = np.arange(12, 24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Broadcasting (на примере сложения)

In [55]:
a = np.array([[2, 5],
              [3, 4],
              [6, 1]])

1 случай -  совпадает только число столбцов

In [56]:
b = np.array([1, 2])

In [57]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

2 случай - совпадает только число строк

In [60]:
c = np.array([[1],
              [2],
              [3]])

In [61]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

### Статистические функции

In [63]:
a = np.random.randint(0, 12, (3, 4))
a

array([[ 2, 11, 10,  0],
       [ 1,  2,  6,  4],
       [ 3,  2,  4, 11]])

In [64]:
a.min()

0

In [66]:
# Минимум  для каждого столбца
a.min(axis = 0)

array([1, 2, 4, 0])

In [68]:
# Максимум для каждой строки
a.max(axis = 1)

array([11,  6, 11])

In [69]:
a.mean(axis = 0)

array([2.        , 5.        , 6.66666667, 5.        ])

In [70]:
a.std(axis = 0)

array([0.81649658, 4.24264069, 2.49443826, 4.54606057])

### Запись и чтение массива из файла

In [71]:
np.save('a.npy', a)

In [72]:
b = np.load('a.npy')

In [73]:
b

array([[ 2, 11, 10,  0],
       [ 1,  2,  6,  4],
       [ 3,  2,  4, 11]])