In [1]:
import numpy as np

In [14]:
A = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
A

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [15]:
A_mean = A.mean(axis=0)
A_mean

array([2. , 8.4])

Результат

In [17]:
A_centered = A - A_mean
A_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])