In [2]:
import numpy as np

In [3]:
A = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
A

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
A_mean = A.mean(axis=0)
A_mean

array([2. , 8.4])

In [5]:
A_centered = A - A_mean
A_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [6]:
A_centered_trans = A_centered.transpose()
A_centered_trans

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [7]:
A_centered_trans1 = A_centered_trans[0]
A_centered_trans2 = A_centered_trans[1]
A_centered_trans1

array([-1.,  0.,  1.,  1., -1.])

In [8]:
A_centered_trans2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [9]:
a_centered_sp = A_centered_trans1 @ A_centered_trans2
a_centered_sp

8.0

In [16]:
A.shape[0]

5

Результат

In [11]:
a_centered_sp / (A.shape[0]-1)

2.0